/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStudyRouteImport } from './routes/_app/study'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoutineRouteImport } from './routes/_app/routine'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppExamsRouteImport } from './routes/_app/exams'
import { Route as AppExamPrepRouteImport } from './routes/_app/exam-prep'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAssignmentsRouteImport } from './routes/_app/assignments'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes.index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses.index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes.$noteId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/_app/courses.$courseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutineRoute = AppRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppExamPrepRoute = AppExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/assignments': typeof AppAssignmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/exam-prep': typeof AppExamPrepRoute
  '/exams': typeof AppExamsRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/routine': typeof AppRoutineRoute
  '/settings': typeof AppSettingsRoute
  '/study': typeof AppStudyRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/assignments': typeof AppAssignmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/exam-prep': typeof AppExamPrepRoute
  '/exams': typeof AppExamsRoute
  '/routine': typeof AppRoutineRoute
  '/settings': typeof AppSettingsRoute
  '/study': typeof AppStudyRoute
  '/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/courses': typeof AppCoursesIndexRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exam-prep': typeof AppExamPrepRoute
  '/_app/exams': typeof AppExamsRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/routine': typeof AppRoutineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/study': typeof AppStudyRoute
  '/_app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/exam-prep'
    | '/exams'
    | '/notes'
    | '/routine'
    | '/settings'
    | '/study'
    | '/courses/$courseId'
    | '/notes/$noteId'
    | '/courses/'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/assignments'
    | '/attendance'
    | '/calendar'
    | '/dashboard'
    | '/exam-prep'
    | '/exams'
    | '/routine'
    | '/settings'
    | '/study'
    | '/courses/$courseId'
    | '/notes/$noteId'
    | '/courses'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/assignments'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/exam-prep'
    | '/_app/exams'
    | '/_app/notes'
    | '/_app/routine'
    | '/_app/settings'
    | '/_app/study'
    | '/_app/courses/$courseId'
    | '/_app/notes/$noteId'
    | '/_app/courses/'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routine': {
      id: '/_app/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AppRoutineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams': {
      id: '/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exam-prep': {
      id: '/_app/exam-prep'
      path: '/exam-prep'
      fullPath: '/exam-prep'
      preLoaderRoute: typeof AppExamPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/courses/$courseId': {
      id: '/_app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamPrepRoute: typeof AppExamPrepRoute
  AppExamsRoute: typeof AppExamsRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppRoutineRoute: typeof AppRoutineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyRoute: typeof AppStudyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExamPrepRoute: AppExamPrepRoute,
  AppExamsRoute: AppExamsRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppRoutineRoute: AppRoutineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyRoute: AppStudyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
